Color picker css styles
Matergi/editorjs-color-picker pull request #4
Opened 2024-12-07 21:49 UTC by QuadVector

- Added class names of container and container elements: `.editorjs__color-selector-container`, `.editorjs__color-selector__container-item`

- Improved styles for the color picker container. Now the color picker items have hover animation and a round style.

The hover effect looks like a smooth increasing of the size of the hovered element.
![image](https://github.com/user-attachments/assets/cd2a37db-925e-43b3-84b7-364710a2f85c)

2024-12-16 12:39 UTC, Matergi requested changes
I really like your change!
If these changes are made, I'll proceed with the merge

2024-12-16 12:39 UTC, Matergi commented on src/styles.css
> +	gap: 10px;
add:
`padding: 4px;`

to fix:
![Screenshot 2024-12-16 at 13 31 22](https://github.com/user-attachments/assets/a297e177-9325-4f3b-9bed-4a8f83dcf56c)

2024-12-16 12:39 UTC, Matergi commented on src/styles.css
> +	transform: scale(1.2);
I’d suggest using `transform: scale(1.1);` instead of 1.2 since it seems that with 1.2 the element enlarges a bit too much

2024-12-16 19:44 UTC, QuadVector commented on src/styles.css
> +	transform: scale(1.2);
Yeah, sure thing! I probably didn't take into overflow property of the container. The scale transform is just for example, you can use opacity instead of it, or something else

2024-12-17 16:06 UTC, Matergi commented
@QuadVector I have released version 1.0.6, thank you for the suggestion!

2024-12-17 16:06 UTC, closed without merging